# Generated by Django 5.2.8 on 2025-11-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_tag_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.URLField(max_length=1024),
        ),
    ]
