# Generated by Django 5.2.8 on 2025-11-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='requests_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
