# Generated by Django 5.2.8 on 2025-11-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_requests_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
