# Generated by Django 5.2.8 on 2025-11-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only')], default='public', max_length=20),
        ),
    ]
