# Generated by Django 5.2.8 on 2025-11-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trainerprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='adopted_comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
