# Generated by Django 5.2.8 on 2025-11-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trainerprofile_adopted_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='public_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
