# Generated by Django 5.2.8 on 2025-11-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_trainerprofile_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
